services:
  anewdawn:
    image: ghcr.io/thelovinator1/anewdawn:latest
    container_name: anewdawn
    env_file: .env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OPENAI_TOKEN=${OPENAI_TOKEN}
    restart: unless-stopped
