name: Build Docker Image

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "@daily"

cache:
  enabled: true
  dir: ""
  host: "192.168.1.127"
  port: 8088

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DISCORD_TOKEN: "0"
      OPENAI_TOKEN: "0"
    if: gitea.event_name != 'pull_request'
    steps:
      - uses: https://github.com/actions/checkout@v4
      - uses: https://github.com/docker/setup-qemu-action@v3
      - uses: https://github.com/docker/setup-buildx-action@v3
      - uses: https://github.com/astral-sh/ruff-action@v3

      - run: docker build --check .
      - run: ruff check --exit-non-zero-on-fix --verbose
      - run: ruff format --check --verbose

      - id: meta
        uses: https://github.com/docker/metadata-action@v5
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
        with:
          images: |
            ghcr.io/thelovinator1/anewdawn
            git.lovinator.space/thelovinator/anewdawn
          tags: type=raw,value=latest,enable=${{ gitea.ref == format('refs/heads/{0}', 'master') }}

      # GitHub Container Registry
      - uses: https://github.com/docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: thelovinator1
          password: ${{ secrets.PACKAGES_WRITE_GITHUB_TOKEN }}

      # Gitea Container Registry
      - uses: https://github.com/docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: git.lovinator.space
          username: thelovinator
          password: ${{ secrets.PACKAGES_WRITE_GITEA_TOKEN }}

      - uses: https://github.com/docker/build-push-action@v6
        with:
          context: .
          push: ${{ gitea.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
