name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: self-hosted
    env:
      DISCORD_TOKEN: "0"
      OPENAI_TOKEN: "0"

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: uv sync --all-extras --dev -U

      - name: Lint the Python code using ruff
        run: ruff check --exit-non-zero-on-fix --verbose

      - name: Check formatting
        run: ruff format --check --verbose

      - name: Lint Dockerfile (build only)
        run: docker build --check .

      - name: Run tests
        run: uv run pytest
